export const appRoutes = {
    home: "/",
    search: "/search",
    recentSearches: "/search/recent",
    learn: "/learn",
    learnGuide: "/learn/guides/:guideSlug",
    learnDetail: "/learn/:slug",
    concerns: "/concerns",
    allergies: "/allergies",
    product: "/products/:barcode",
    dataAndLicenses: "/data-and-licenses",
    labels: "/labels",
    labelsRead: "/labels/read",
    labelsCompare: "/labels/compare",
    compare: "/labels/compare",
    photoComparison: "/labels/compare",
    legacyCompare: "/compare",
} as const
