"""OFF-only Package Match use case, contracts, and API router."""

from lifegoods.package_matches.assessments import (
    AllergenAssessmentCache,
    AllergenAssessmentEvaluation,
    AllergenAssessmentEvaluator,
    AllergenAssessmentOutcome,
    AllergenAssessmentReason,
    AllergenAssessmentStatus,
    AllergenConceptOutcome,
    AllergenDeterministicMatcher,
    AllergenFinding,
    DefaultAllergenDeterministicMatcher,
    DefaultOffAllergenEvidenceExtractor,
    DisabledAllergenAssessmentEvaluator,
    EvidenceCoverageState,
    OffAllergenEvidenceExtractor,
    StandardAllergenAssessmentEvaluator,
)
from lifegoods.package_matches.cache import (
    DEFAULT_ASSESSMENT_CACHE_TTL_SECONDS,
    RedisAllergenAssessmentCache,
    assessment_cache_key_for_record,
    build_assessment_cache_key,
    compute_evidence_digest,
    deserialize_assessment_evaluation,
    serialize_assessment_evaluation,
)
from lifegoods.package_matches.contracts import (
    AllergenAssessmentResponse,
    AllergenConceptOutcomeResponse,
    AllergenFindingResponse,
    AssessmentReferenceDatasetVersionResponse,
    ExternalDatasetVersionResponse,
    OpenFoodFactsLookupResponse,
    PackageMatchCandidateResponse,
    PackageMatchesResponse,
    PackageMatchEvidenceResponse,
    PackageMatchReferenceImageResponse,
    PackageMatchSourceResponse,
    PackageSearchAdditiveResponse,
    PackageSearchNameResponse,
    PackageSearchResponse,
    PackageSearchResultResponse,
)
from lifegoods.package_matches.dependencies import (
    get_finder,
    get_rate_limiter,
    get_search_rate_limiter,
    get_searcher,
)
from lifegoods.package_matches.models import (
    OpenFoodFactsLookup,
    OpenFoodFactsLookupStatus,
    PackageMatchCandidate,
    PackageMatchEvidence,
    PackageMatchReferenceImage,
    PackageMatchResult,
    PackageMatchSourceKind,
    PackageMatchSourceMetadata,
    PackageMatchSourceUnavailableError,
)
from lifegoods.package_matches.rate_limit import (
    PackageMatchRateLimiter,
    RedisPackageMatchRateLimiter,
)
from lifegoods.package_matches.router import router
from lifegoods.package_matches.search import (
    MongoPackageSearch,
    PackageSearch,
    SearchHit,
    SearchPage,
    SearchValidationError,
    build_search_index,
)
from lifegoods.package_matches.service import FindPackageMatches
from lifegoods.reference_datasets import AllergenReferenceDataAccess

__all__ = [
    "AllergenAssessmentCache",
    "AllergenAssessmentEvaluation",
    "AllergenAssessmentEvaluator",
    "AllergenAssessmentOutcome",
    "AllergenAssessmentReason",
    "AllergenAssessmentStatus",
    "AllergenAssessmentResponse",
    "AllergenConceptOutcome",
    "AllergenConceptOutcomeResponse",
    "AllergenDeterministicMatcher",
    "AllergenFinding",
    "AllergenFindingResponse",
    "AllergenReferenceDataAccess",
    "AssessmentReferenceDatasetVersionResponse",
    "DEFAULT_ASSESSMENT_CACHE_TTL_SECONDS",
    "DefaultAllergenDeterministicMatcher",
    "DefaultOffAllergenEvidenceExtractor",
    "DisabledAllergenAssessmentEvaluator",
    "EvidenceCoverageState",
    "ExternalDatasetVersionResponse",
    "FindPackageMatches",
    "OffAllergenEvidenceExtractor",
    "OpenFoodFactsLookup",
    "OpenFoodFactsLookupResponse",
    "OpenFoodFactsLookupStatus",
    "PackageMatchCandidate",
    "PackageMatchCandidateResponse",
    "PackageMatchEvidence",
    "PackageMatchEvidenceResponse",
    "PackageMatchReferenceImage",
    "PackageMatchReferenceImageResponse",
    "PackageMatchRateLimiter",
    "PackageMatchResult",
    "PackageMatchSourceKind",
    "PackageMatchSourceMetadata",
    "PackageMatchSourceResponse",
    "PackageMatchSourceUnavailableError",
    "PackageMatchesResponse",
    "PackageSearch",
    "PackageSearchAdditiveResponse",
    "PackageSearchNameResponse",
    "PackageSearchResponse",
    "PackageSearchResultResponse",
    "RedisAllergenAssessmentCache",
    "RedisPackageMatchRateLimiter",
    "StandardAllergenAssessmentEvaluator",
    "assessment_cache_key_for_record",
    "build_assessment_cache_key",
    "compute_evidence_digest",
    "deserialize_assessment_evaluation",
    "get_finder",
    "get_rate_limiter",
    "get_search_rate_limiter",
    "get_searcher",
    "MongoPackageSearch",
    "SearchHit",
    "SearchPage",
    "SearchValidationError",
    "build_search_index",
    "router",
    "serialize_assessment_evaluation",
]
