"""OFF-only Package Match use case, contracts, and API router."""

from lifegoods.package_matches.assessments import (
    AllergenAssessmentEvaluation,
    AllergenAssessmentEvaluator,
    AllergenAssessmentOutcome,
    AllergenAssessmentReason,
    AllergenConceptOutcome,
    AllergenDeterministicMatcher,
    AllergenFinding,
    DefaultAllergenDeterministicMatcher,
    DefaultOffAllergenEvidenceExtractor,
    DisabledAllergenAssessmentEvaluator,
    EvidenceCoverageState,
    OffAllergenEvidenceExtractor,
    StandardAllergenAssessmentEvaluator,
)
from lifegoods.package_matches.contracts import (
    AllergenAssessmentResponse,
    AllergenConceptOutcomeResponse,
    AllergenFindingResponse,
    AssessmentReferenceDatasetVersionResponse,
    ExternalDatasetVersionResponse,
    OpenFoodFactsLookupResponse,
    PackageMatchCandidateResponse,
    PackageMatchesResponse,
    PackageMatchEvidenceResponse,
    PackageMatchReferenceImageResponse,
    PackageMatchSourceResponse,
)
from lifegoods.package_matches.models import (
    OpenFoodFactsLookup,
    OpenFoodFactsLookupStatus,
    PackageMatchCandidate,
    PackageMatchEvidence,
    PackageMatchReferenceImage,
    PackageMatchResult,
    PackageMatchSourceKind,
    PackageMatchSourceMetadata,
    PackageMatchSourceUnavailableError,
)
from lifegoods.package_matches.router import get_finder, get_rate_limiter, router
from lifegoods.package_matches.service import FindPackageMatches
from lifegoods.reference_datasets import AllergenReferenceDataAccess

__all__ = [
    "AllergenAssessmentEvaluation",
    "AllergenAssessmentEvaluator",
    "AllergenAssessmentOutcome",
    "AllergenAssessmentReason",
    "AllergenAssessmentResponse",
    "AllergenConceptOutcome",
    "AllergenConceptOutcomeResponse",
    "AllergenDeterministicMatcher",
    "AllergenFinding",
    "AllergenFindingResponse",
    "AllergenReferenceDataAccess",
    "AssessmentReferenceDatasetVersionResponse",
    "DefaultAllergenDeterministicMatcher",
    "DefaultOffAllergenEvidenceExtractor",
    "DisabledAllergenAssessmentEvaluator",
    "EvidenceCoverageState",


    "ExternalDatasetVersionResponse",
    "FindPackageMatches",
    "OffAllergenEvidenceExtractor",
    "OpenFoodFactsLookup",
    "OpenFoodFactsLookupResponse",
    "OpenFoodFactsLookupStatus",
    "PackageMatchCandidate",
    "PackageMatchCandidateResponse",
    "PackageMatchEvidence",
    "PackageMatchEvidenceResponse",
    "PackageMatchReferenceImage",
    "PackageMatchReferenceImageResponse",
    "PackageMatchResult",
    "PackageMatchSourceKind",
    "PackageMatchSourceMetadata",
    "PackageMatchSourceResponse",
    "PackageMatchSourceUnavailableError",
    "PackageMatchesResponse",
    "StandardAllergenAssessmentEvaluator",
    "get_finder",
    "get_rate_limiter",
    "router",
]
