"""Contracts and local services for the opt-in package-photo comparison prototype.

The standalone app is intentionally separate from the ordinary Life Goods API;
this package does not add routes, storage, or persistence to that app.
"""

from lifegoods.photo_comparison.contracts import (
    MAX_COMPARISON_REQUEST_BYTES,
    MAX_PHOTOS_PER_PRODUCT,
    ComparisonRequest,
    ComparisonResponse,
    ComparisonRow,
    ComparisonState,
    DerivationInput,
    DerivationInputKind,
    DerivedValue,
    Extraction,
    ExtractionOutcome,
    FieldObservation,
    FieldState,
    ImageEvidence,
    ImageRegion,
    MeasurementUnit,
    NutritionBasis,
    NutritionColumn,
    ObservationAlternative,
    PhotoComparisonErrorCode,
    PhotoComparisonErrorDetail,
    PhotoComparisonErrorResponse,
    PreparationState,
    Quantity,
    ReportedValue,
)

__all__ = [
    "MAX_COMPARISON_REQUEST_BYTES",
    "MAX_PHOTOS_PER_PRODUCT",
    "ComparisonRequest",
    "ComparisonResponse",
    "ComparisonRow",
    "ComparisonState",
    "DerivedValue",
    "DerivationInput",
    "DerivationInputKind",
    "Extraction",
    "ExtractionOutcome",
    "FieldObservation",
    "FieldState",
    "ImageEvidence",
    "ImageRegion",
    "MeasurementUnit",
    "NutritionBasis",
    "NutritionColumn",
    "ObservationAlternative",
    "PhotoComparisonErrorCode",
    "PhotoComparisonErrorDetail",
    "PhotoComparisonErrorResponse",
    "PreparationState",
    "Quantity",
    "ReportedValue",
]
